[tool.briefcase]
project_name = "NewGAN Manager"
bundle = "com.fm"
version = "1.0.0"
url = "https://google.de"
license = "GNU General Public License v3 (GPLv3)"
author = 'Maradonna (gestalt)'
author_email = "None"

[tool.briefcase.app.newganmanager]
formal_name = "NewGAN Manager"
description = "NewGAN Replacement Management Tool"
icon = "src/newganmanager/resources/logo"
sources = ['src/newganmanager', 'views']
requires = ["dhooks==1.1.4"]

[tool.briefcase.app.newganmanager.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev18',
]

[tool.briefcase.app.newganmanager.linux]
requires = [
    'toga-gtk>=0.3.0.dev18',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.newganmanager.windows]
requires = [
    'toga-winforms>=0.3.0.dev18',
]

# Mobile deployments
[tool.briefcase.app.newganmanager.iOS]
requires = [
    'toga-iOS>=0.3.0.dev18',
]

[tool.briefcase.app.newganmanager.android]
requires = [
    'toga-android>=0.3.0.dev18',
]
